### ISSUE TITLE
Black boxes around textures

### ISSUE THREAD

**Issue by apidya** [devint1/Descent2-Mobile#18]
Transparency isn't rendered on bitmaps. e.g. Laser/missile impacts, cockpit view

**Comment by devint1** [comment]
You might need to change the values [here](https://github.com/devint1/Descent2-Mobile/blob/master/2d/gr.h#L25-L26). I have the Mac version of the game files, which if I understand correctly, swaps 255/0 as the transparency color. Therefore, changing that to `#define SWAP_0_255 0` might fix it.

It might be a small quality-of-life improvement to automatically select the correct value somehow, but for now, the correct behavior relies on manually changing these flags. I'm going to close this for now, but please reply if you're still having issues.
